name: GitHub CI Pipeline
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: actions/checkout@v4
- name: Display Message
run: echo &quot;Build Started&quot;
- name: List Files
run: ls
- name: Build Successful
run: echo &quot;Build Completed Successfully&quot;